# Generated by Django 4.2.1 on 2023-07-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='despcription',
            new_name='description',
        ),
    ]
